### ISSUE TITLE
EntLib 6.0 is missing and generation fails

### ISSUE THREAD

**Issue by niemyjski** [netTiers/netTiers#489]
I was just doing a round of testing and noticed enterprise lib 6 is missing.

---------------- Generation started -----------------
Error: Could not find a part of the path 'D:\Code\netTiers\Source\References\EntLibv6_0\Microsoft.Practices.EnterpriseLibrary.Common.dll'.
Stack Trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at MoM.Templates.CommonSqlCode.SafeCopyFile(String path, String destination) in D:\Code\netTiers\Source\TemplateLib\CommonSqlCode.cs:line 5092
   at _CodeSmith.NetTiers_cst.Go() in D:\Code\netTiers\Source\NetTiers.cst:line 1303
   at _CodeSmith.NetTiers_cst.__RenderMethod1(TextWriter writer, Control control) in D:\Code\netTiers\Source\NetTiers.cst:line 5464
   at CodeSmith.Engine.Control.RenderChildren(TextWriter writer)
   at CodeSmith.Engine.CodeTemplate.Render(TextWriter writer)
   at CodeSmith.Engine.CodeTemplate.RenderToString()
   at CodeSmith.Engine.Remoting.TemplateSession.#8l()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Build complete -- 1 errors, 0 warnings

---------------------- Done ----------------------

**Comment by niemyjski** [comment]
Also, would be good to fix the links from http://nettiers.net to this github repo

**Comment by jeremeguenther** [comment]
I do have those files, I could email them to you.

Unfortunately the rejection of my last pull request has my local database in a state of conflict, and github is such a nightmare to work with that I have not taken the time to try and figure out how to fix it or piecemeal push stuff.

According to my local diff it looks like I might have several outstanding bug fixes and feature enhancements, i'm just not sure when i'll have the hours needed to work through the github issues unless they release a better set of tools to work with it.  GitHub Desktop just doesn't work very well, and unless you live in it the command line is next to worthless.

**Comment by jeremeguenther** [comment]
[EntLibv6_0.zip](https://github.com/netTiers/netTiers/files/9560051/EntLibv6_0.zip)

Attached is the zip file with the missing folder.

**Comment by niemyjski** [comment]
Thanks for the files, hope all is well! The rejection of the last pr? I'd almost clone fresh and then use something like BeyondCompare to bring back changes. I also mainly use GitKraken which is amazing!

I've fixed the links (lots of changes to samples due to vs code) but I made sure the templates didn't have any extra changes.
